=== samsween/backend-project-grocery/server/xml/Employee/employee.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (Username, Password)>
<!ELEMENT Username (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ATTLIST employee Empid ID #REQUIRED>

=== samsween/backend-project-grocery/server/xml/Employee/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="styles.css" type="text/css"?>
<!DOCTYPE employees SYSTEM "employee.dtd">

<employees>
    <employee Empid="x100">
        <Username>Username</Username>
        <Password>Password</Password>
    </employee>
    <employee Empid="x101">
        <Username>Jam21 </Username>
        <Password>Axgp231@!</Password>
    </employee>
    <employee Empid="x102">
        <Username>Luc43 </Username>
        <Password>Axgp231@! </Password>
    </employee>
    <employee Empid="x103">
        <Username>Jam22 </Username>
        <Password>aXgp231@!</Password>
    </employee>
    <employee Empid="x104">
        <Username> Jam23 </Username>
        <Password> Aaxgp231@! </Password>
    </employee>
    <employee Empid="x105">
        <Username>Luc44 </Username>
        <Password>Axgp431@! </Password>
    </employee>
    <employee Empid="x106">
        <Username>Luc45</Username>
        <Password>AxGP7831@! </Password>
    </employee>
    <employee Empid="x107">
        <Username>Jam24 </Username>
        <Password>Axgp231@!34</Password>
    </employee>
</employees>
